server:
  port: 8081

spring:
  application:
    name: orderServer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos注册中心地址
        ephemeral: false  #临时实例

    sentinel:
      transport:
        dashboard: localhost:8858 #监控页面地址
      web-context-unify: false
      block-page: /api/order/blocked

seata:
  service:
    vgroup-mapping:
      # 这里需要对事务组做映射，默认的分组名为 应用名称-seata-service-group，将其映射到default集群
      # 这个很关键，一定要配置对，不然会找不到服务
      orderService-seata-service-group: default
    grouplist:
      default: localhost:8868