server:
  port: 8080

spring:
  application:
    name: gatewayServer

  cloud:
    gateway:
      # 配置路由列表，每一项都包含了很多信息
      routes:
      - id: orderServer   # 路由名称
        uri: lb://orderServer  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
        predicates: # 路由规则，断言什么请求会被路由
        - Path=/api/order/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务

      - id: payServer
        uri: lb://payServer
        predicates:
        - Path=/api/pay/**

    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos注册中心地址
        ephemeral: false  #临时实例

    sentinel:
      transport:
        dashboard: localhost:8858 #监控页面地址

